plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'br.com.strongapp'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "br.com.strongapp"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.recyclerview
    implementation libs.swiperefreshlayout
    implementation libs.fragment
    implementation libs.retrofit
    implementation libs.retrofit.gson
    implementation libs.okhttp.logging
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}
